//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_COUNTRY
    {
        public TBL_COUNTRY()
        {
            this.TBL_STATE = new HashSet<TBL_STATE>();
        }
    
        public string COUNTRY_NAME { get; set; }
        public decimal ID { get; set; }
    
        public virtual ICollection<TBL_STATE> TBL_STATE { get; set; }
    }
}
