//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EMP_BASICINFO
    {
        public TBL_EMP_BASICINFO()
        {
            this.TBL_EMP_ASSETDETAILS = new HashSet<TBL_EMP_ASSETDETAILS>();
            this.TBL_EMP_COM_DETAILS_HISTORY = new HashSet<TBL_EMP_COM_DETAILS_HISTORY>();
            this.TBL_EMP_DOCUMENT_DETAILS = new HashSet<TBL_EMP_DOCUMENT_DETAILS>();
            this.TBL_EMP_COMMUNICATION_DETAILS = new HashSet<TBL_EMP_COMMUNICATION_DETAILS>();
            this.TBL_EMP_EMPLOYMENT_RECORD = new HashSet<TBL_EMP_EMPLOYMENT_RECORD>();
            this.TBL_EMP_PIPDETAILS = new HashSet<TBL_EMP_PIPDETAILS>();
            this.TBL_EMP_QUALIFICATION_DETAILS = new HashSet<TBL_EMP_QUALIFICATION_DETAILS>();
            this.TBL_EMP_RELATIONSHIP_DETAILS = new HashSet<TBL_EMP_RELATIONSHIP_DETAILS>();
            this.TBL_EMP_TRANSFER_DETAILS = new HashSet<TBL_EMP_TRANSFER_DETAILS>();
            this.TBL_EMP_LEAVE_DETAILS = new HashSet<TBL_EMP_LEAVE_DETAILS>();
            this.TBL_EMP_BASICINFO_HISTORY = new HashSet<TBL_EMP_BASICINFO_HISTORY>();
            this.TBL_EMP_TRAINING_DETAILS = new HashSet<TBL_EMP_TRAINING_DETAILS>();
            this.TBL_EMP_EXTRACULMACTIVITY = new HashSet<TBL_EMP_EXTRACULMACTIVITY>();
        }
    
        public decimal ID { get; set; }
        public string EMPLOYEE_CODE { get; set; }
        public Nullable<decimal> DESIGNATION { get; set; }
        public string EMPLOYEE_FIRSTNAME { get; set; }
        public string EMPLOYEE_MIDDLENAME { get; set; }
        public string EMPLOYEE_LASTNAME { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public string AGE { get; set; }
        public string SEX { get; set; }
        public string DOMICILE_STATUS { get; set; }
        public string MATERIAL_STATUS { get; set; }
        public Nullable<System.DateTime> WEDDING_ANNIVERSARY { get; set; }
        public string REPORTING_TO { get; set; }
        public Nullable<decimal> GRADE { get; set; }
        public Nullable<decimal> BLOOD_GROUP { get; set; }
        public string HEIGHT { get; set; }
        public string WEIGHT { get; set; }
        public string MEDICLAIM_NUMBER { get; set; }
        public string ESIC_NO { get; set; }
        public string PF_UNID_NUMBER { get; set; }
        public string INDUCTION { get; set; }
        public string IDENTIFICATION_MARK { get; set; }
        public string LAST_MAJOR_ILLNESS_SURGERY { get; set; }
        public string ALLERGY_HISTORY { get; set; }
        public string PHYSICAL_DISABILITY { get; set; }
        public string HIRING_TYPE { get; set; }
        public string CV_TYPE { get; set; }
        public string YEAR_OF_EXPERIENCE { get; set; }
        public Nullable<System.DateTime> EXIT_DATE { get; set; }
        public Nullable<decimal> EXIT_TYPE { get; set; }
        public string REFERENCE { get; set; }
        public string FULL_N_FINAL_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATETIME { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATETIME { get; set; }
        public string DIVISION { get; set; }
        public string SUBDIVISION { get; set; }
        public string SECTION { get; set; }
        public Nullable<decimal> DEPARTMENT { get; set; }
        public string EMPLOYEE_IMAGE { get; set; }
        public string ISDELETED { get; set; }
        public string DELETEDBY { get; set; }
        public Nullable<System.DateTime> DELETEDDATETIME { get; set; }
        public Nullable<System.DateTime> JOINING_DATE { get; set; }
        public string RELIGION { get; set; }
        public Nullable<decimal> WORKLOCATION { get; set; }
        public string MOTHERTOUNGE { get; set; }
        public byte[] EMPIMG { get; set; }
        public Nullable<decimal> EXITCATAGORY { get; set; }
        public string STATUS { get; set; }
        public string REPORTINGPERSONID { get; set; }
        public Nullable<System.DateTime> RESIGNATIONDATE { get; set; }
        public string LEAVEENCASHMENT { get; set; }
    
        public virtual ICollection<TBL_EMP_ASSETDETAILS> TBL_EMP_ASSETDETAILS { get; set; }
        public virtual TBL_HRMS_LOCATIONMASTER TBL_HRMS_LOCATIONMASTER { get; set; }
        public virtual TBL_HRMS_BLOODGROUP_MASTER TBL_HRMS_BLOODGROUP_MASTER { get; set; }
        public virtual ICollection<TBL_EMP_COM_DETAILS_HISTORY> TBL_EMP_COM_DETAILS_HISTORY { get; set; }
        public virtual TBL_HRMS_DEPARTMENTMASTER TBL_HRMS_DEPARTMENTMASTER { get; set; }
        public virtual ICollection<TBL_EMP_DOCUMENT_DETAILS> TBL_EMP_DOCUMENT_DETAILS { get; set; }
        public virtual ICollection<TBL_EMP_COMMUNICATION_DETAILS> TBL_EMP_COMMUNICATION_DETAILS { get; set; }
        public virtual ICollection<TBL_EMP_EMPLOYMENT_RECORD> TBL_EMP_EMPLOYMENT_RECORD { get; set; }
        public virtual TBL_HRMS_EXITTYPE_MASTER TBL_HRMS_EXITTYPE_MASTER { get; set; }
        public virtual TBL_HRMS_GRADE_MASTER TBL_HRMS_GRADE_MASTER { get; set; }
        public virtual ICollection<TBL_EMP_PIPDETAILS> TBL_EMP_PIPDETAILS { get; set; }
        public virtual ICollection<TBL_EMP_QUALIFICATION_DETAILS> TBL_EMP_QUALIFICATION_DETAILS { get; set; }
        public virtual ICollection<TBL_EMP_RELATIONSHIP_DETAILS> TBL_EMP_RELATIONSHIP_DETAILS { get; set; }
        public virtual ICollection<TBL_EMP_TRANSFER_DETAILS> TBL_EMP_TRANSFER_DETAILS { get; set; }
        public virtual ICollection<TBL_EMP_LEAVE_DETAILS> TBL_EMP_LEAVE_DETAILS { get; set; }
        public virtual TBL_HRMS_DESIGNATIONMASTER TBL_HRMS_DESIGNATIONMASTER { get; set; }
        public virtual ICollection<TBL_EMP_BASICINFO_HISTORY> TBL_EMP_BASICINFO_HISTORY { get; set; }
        public virtual ICollection<TBL_EMP_TRAINING_DETAILS> TBL_EMP_TRAINING_DETAILS { get; set; }
        public virtual ICollection<TBL_EMP_EXTRACULMACTIVITY> TBL_EMP_EXTRACULMACTIVITY { get; set; }
    }
}
