//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HRMS_REPORTINGMASTER
    {
        public decimal ID { get; set; }
        public Nullable<decimal> DEPARTMENT_ID { get; set; }
        public Nullable<decimal> EMPLOYEE_ID { get; set; }
        public string REPORTING_PERSON_NAME { get; set; }
        public string CREATEDBY { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATETIME { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATETIME { get; set; }
        public string ISDELETED { get; set; }
        public string DELETEDBY { get; set; }
        public Nullable<System.DateTime> DELETEDDATETIME { get; set; }
    }
}
