//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EMP_HOBBIES
    {
        public decimal ID { get; set; }
        public string HOBBIES { get; set; }
        public Nullable<decimal> EMPLOYEEID { get; set; }
    }
}
