//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HRMS_RECORDTYPE_MASTER
    {
        public TBL_HRMS_RECORDTYPE_MASTER()
        {
            this.TBL_EMP_DOCUMENT_DETAILS = new HashSet<TBL_EMP_DOCUMENT_DETAILS>();
        }
    
        public decimal ID { get; set; }
        public string RECORDTYPE_NAME { get; set; }
    
        public virtual ICollection<TBL_EMP_DOCUMENT_DETAILS> TBL_EMP_DOCUMENT_DETAILS { get; set; }
    }
}
