//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SECTION
    {
        public string SUB_DIV_CODE { get; set; }
        public string SEC_CODE { get; set; }
        public string SEC_NAME { get; set; }
        public string DISPLAY_CODE { get; set; }
        public string CESU_DIV_CODE { get; set; }
        public string CESU_SUB_DIV_CODE { get; set; }
        public string CESU_SEC_CODE { get; set; }
        public string UTILITY_NAME { get; set; }
        public string UTILITY_DIV_NAME { get; set; }
        public string UTILIT_SUB_DIV_NAME { get; set; }
    
        public virtual TBL_SUB_DIVISION TBL_SUB_DIVISION { get; set; }
    }
}
