//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DIVISION
    {
        public TBL_DIVISION()
        {
            this.TBL_SUB_DIVISION = new HashSet<TBL_SUB_DIVISION>();
        }
    
        public string CIRCLE_CODE { get; set; }
        public string DIVISION_CODE { get; set; }
        public string DIV_NAME { get; set; }
        public string DISPLAY_CODE { get; set; }
        public string CENTER_NAME { get; set; }
        public string UTILITY_NAME { get; set; }
    
        public virtual ICollection<TBL_SUB_DIVISION> TBL_SUB_DIVISION { get; set; }
    }
}
