//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EMP_TRANSFER_DETAILS
    {
        public decimal ID { get; set; }
        public Nullable<decimal> EMPLOYEE_ID { get; set; }
        public Nullable<decimal> DESIGNATION_ID { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public string DIVISION { get; set; }
        public string SUB_DIVISION { get; set; }
        public string SECTION { get; set; }
        public string STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATETIME { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATETIME { get; set; }
        public string ISDELETED { get; set; }
        public string DELETEDBY { get; set; }
        public string DELETEDDATETIME { get; set; }
        public Nullable<decimal> REPORTING_PERSON { get; set; }
        public Nullable<decimal> DEPARTMENT { get; set; }
        public Nullable<decimal> WORK_LOCATION { get; set; }
        public Nullable<decimal> GRADEID { get; set; }
        public string REPORTINGPERNAME { get; set; }
        public string REMARKS { get; set; }
    
        public virtual TBL_EMP_BASICINFO TBL_EMP_BASICINFO { get; set; }
        public virtual TBL_HRMS_DESIGNATIONMASTER TBL_HRMS_DESIGNATIONMASTER { get; set; }
        public virtual TBL_HRMS_DEPARTMENTMASTER TBL_HRMS_DEPARTMENTMASTER { get; set; }
        public virtual TBL_HRMS_LOCATIONMASTER TBL_HRMS_LOCATIONMASTER { get; set; }
        public virtual TBL_HRMS_GRADE_MASTER TBL_HRMS_GRADE_MASTER { get; set; }
    }
}
