//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_STATE
    {
        public TBL_STATE()
        {
            this.TBL_EMP_COM_DETAILS_HISTORY = new HashSet<TBL_EMP_COM_DETAILS_HISTORY>();
            this.TBL_EMP_COM_DETAILS_HISTORY1 = new HashSet<TBL_EMP_COM_DETAILS_HISTORY>();
            this.TBL_EMP_COMMUNICATION_DETAILS = new HashSet<TBL_EMP_COMMUNICATION_DETAILS>();
            this.TBL_EMP_COMMUNICATION_DETAILS1 = new HashSet<TBL_EMP_COMMUNICATION_DETAILS>();
        }
    
        public string STATE_NAME { get; set; }
        public decimal ID { get; set; }
        public Nullable<decimal> COUNTRY_ID { get; set; }
    
        public virtual TBL_COUNTRY TBL_COUNTRY { get; set; }
        public virtual ICollection<TBL_EMP_COM_DETAILS_HISTORY> TBL_EMP_COM_DETAILS_HISTORY { get; set; }
        public virtual ICollection<TBL_EMP_COM_DETAILS_HISTORY> TBL_EMP_COM_DETAILS_HISTORY1 { get; set; }
        public virtual ICollection<TBL_EMP_COMMUNICATION_DETAILS> TBL_EMP_COMMUNICATION_DETAILS { get; set; }
        public virtual ICollection<TBL_EMP_COMMUNICATION_DETAILS> TBL_EMP_COMMUNICATION_DETAILS1 { get; set; }
    }
}
