//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EMP_DOCUMENT_DETAILS
    {
        public decimal ID { get; set; }
        public Nullable<decimal> EMPLOYEE_RECORD_TYPE { get; set; }
        public string DOCUMENT_PATH { get; set; }
        public Nullable<decimal> EMPLOYEE_ID { get; set; }
        public string CREATEDBY { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATETIME { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATETIME { get; set; }
        public string ISDELETED { get; set; }
        public string DELETEDBY { get; set; }
        public Nullable<System.DateTime> DELETEDDATETIME { get; set; }
    
        public virtual TBL_EMP_BASICINFO TBL_EMP_BASICINFO { get; set; }
        public virtual TBL_HRMS_RECORDTYPE_MASTER TBL_HRMS_RECORDTYPE_MASTER { get; set; }
    }
}
