//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA_LAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public decimal USERID { get; set; }
        public string USERNAME { get; set; }
        public string USERPASSWORD { get; set; }
        public string SECURITYQUESTION { get; set; }
        public string ANSWER { get; set; }
        public decimal GROUPID { get; set; }
        public Nullable<decimal> EMPID { get; set; }
        public string ACCESS_AUTH { get; set; }
    }
}
